### ISSUE TITLE
patch the template of Superset's login page

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/EpiGraphHub#28]
from @fccoelho 

> We need to patch the template of Superset's login page, with our custom whenever redeploying. Also the custom template should live somewhere in this project where it can easily be updated. A Makefile command to re-apply the patch in production whenever it is updated, is a good thing to have.

**Comment by fccoelho** [comment]
The template that needs updating is [this one](https://github.com/apache/superset/blob/9773aba522e957ed9423045ca153219638a85d2f/superset/templates/superset/public_welcome.html).

It should be maintained here, in this repository, so that Superset installation can be patched with it  at every new release.
